#include "computeCellValues.h"
#include "helper.h"
#include <stdio.h>
#include "visualLB.h"

void write_vtkHeader( FILE *fp, int xlength) {
  if( fp == NULL ){
    char szBuff[80];
    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;
  }

  fprintf(fp,"# vtk DataFile Version 2.0\n");
  fprintf(fp,"generated by CFD-lab course output (written by Denys Korzh, Denys Sobchyshak, Ozel Christo Annamanthadoo  \n");
  fprintf(fp,"ASCII\n");
  fprintf(fp,"\n");
  fprintf(fp,"DATASET STRUCTURED_GRID\n");
  fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength, xlength, xlength);
  fprintf(fp,"POINTS %i float\n", xlength*xlength*xlength );
  fprintf(fp,"\n");
}


void write_vtkPointCoordinates( FILE *fp, int xlength) {
  double originX = 0.0;
  double originY = 0.0;

  int i = 0;
  int j = 0;
  int k = 0;

  for(k = 0; k < xlength; k++) {
    for(j = 0; j < xlength; j++) {
      for(i = 0; i < xlength; i++) {
        fprintf(fp, "%f %f %f\n", originX+(i*1.0/xlength), originY+(j*1.0/xlength), originY+(k*1.0/xlength) );
      }
    }
  }
}

/* NOTE: We output only the fluid cells */
void writeVtkOutput(const double * const collideField, const int * const flagField, const char * filename, unsigned int t, int xlength) {
  int i, j, k;
  double velocity[3];
  double density;
  /* len is used to set values in lexicographic order "[ Q * ( z*len*len + y*len + x) + i ]" */
  int len = xlength + 2;

  char szFileName[80];
  FILE *fp=NULL;
  sprintf( szFileName, "%s.%i.vtk", filename, t );
  fp = fopen( szFileName, "w");
  if( fp == NULL ){
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }

  write_vtkHeader( fp, xlength);
  write_vtkPointCoordinates( fp, xlength);

  fprintf(fp,"POINT_DATA %i \n", xlength*xlength*xlength );

  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(k = 1; k < xlength+1; k++) {
    for(j = 1; j < xlength+1; j++) {
      for(i = 1; i < xlength+1; i++) {
        computeDensity (&collideField[ 19 * ( k*len*len + j*len + i) ], &density);
        computeVelocity(&collideField[ 19 * ( k*len*len + j*len + i) ], &density, velocity);
        fprintf(fp, "%f %f %f\n",  velocity[0], velocity[1], velocity[2]);
      }
    }
  }

  fprintf(fp,"\n");
  fprintf(fp, "SCALARS density float 1 \n");
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(k = 1; k < xlength+1; k++) {
    for(j = 1; j < xlength+1; j++) {
      for(i = 1; i < xlength+1; i++) {
        computeDensity (&collideField[ 19 * ( k*len*len + j*len + i) ], &density);
        fprintf(fp, "%f\n",  density);
      }
    }
  }

  if(fclose(fp)){
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }
}