#include "LBDefinitions.h"
#include "computeCellValues.h"
#include "helper.h"
#include <stdio.h>
#include "visualLB.h"

void write_vtkHeader(FILE *fp, int *xlength) {
    if(fp == NULL){
        char szBuff[80];
        sprintf(szBuff,"Null pointer in write_vtkHeader");
        ERROR(szBuff);
        return;
    }

    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"generated by CFD-lab course output (written by Denys Korzh, Denys Sobchyshak, Ozel Christo Annamanthadoo  \n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");
    fprintf(fp,"DATASET STRUCTURED_GRID\n");
    fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength[0], xlength[1], xlength[2]);
    fprintf(fp,"POINTS %i float\n", xlength[0]*xlength[1]*xlength[2] );
    fprintf(fp,"\n");
}

void write_vtkPointCoordinates(FILE *fp, int *xlength) {
    double origin_x=0.0, origin_y=0.0, origin_z=0.0;
    int i, j, k;

    for(k=0; k<xlength[2]; k++) {
        for(j=0; j<xlength[1]; j++) {
            for(i=0; i<xlength[0]; i++) {
                fprintf(fp, "%f %f %f\n", origin_x+(i*1.0/xlength[2]),origin_y+(j*1.0/xlength[2]), 
                        origin_z+(k*1.0/xlength[2]));
            }
        }
    }
}

/* NOTE: We output only the fluid cells */
void writeVtkOutput(const double * const collide_field, const int * const flag_field, 
        const char * file_name, unsigned int t, int *xlength) {
    int i, j, k;
    double velocity[3], density;
    /* len is used to set values in lexicographic order "[ Q * ( z*len*len + y*len + x) + i ]" */
    int len_x=xlength[0]+2, len_y=xlength[1]+2, len_z=xlength[2]+2;
    char szFileName[80];

    FILE *fp=NULL;
    sprintf( szFileName, "%s.%i.vtk", file_name, t );
    fp = fopen( szFileName, "w");
    if( fp == NULL ){
        char szBuff[80];
        sprintf( szBuff, "Failed to open %s", szFileName );
        ERROR( szBuff );
        return;
    }

    write_vtkHeader(fp,xlength);
    write_vtkPointCoordinates(fp,xlength);

    fprintf(fp,"POINT_DATA %i \n",xlength[0]*xlength[1]*xlength[2] );
    fprintf(fp,"\n");
    fprintf(fp,"VECTORS velocity float\n");
    for(k = 1; k < len_z-1; k++) {
        for(j = 1; j < len_y-1; j++) {
            for(i = 1; i < len_x-1; i++) {
                if( flag_field[k*len_x*len_y + j*len_x + i] == FLUID ) {
                    computeDensity (&collide_field[19*( k*len_x*len_y+j*len_x+i)],&density);
                    computeVelocity(&collide_field[19*( k*len_x*len_y+j*len_x+i)],&density,velocity);
                    fprintf(fp,"%f %f %f\n",velocity[0],velocity[1],velocity[2]);
                } else { /* For obstacles */
                    fprintf(fp,"%f %f %f\n",0.0, 0.0, 0.0);
                }
            }
        }
    }

    fprintf(fp,"\n");
    fprintf(fp, "SCALARS density float 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");
    for(k = 1; k < len_z-1; k++) {
        for(j = 1; j < len_y-1; j++) {
            for(i = 1; i < len_x-1; i++) {
                if( flag_field[k*len_x*len_y + j*len_x + i] == FLUID ) {
                    computeDensity (&collide_field[19*( k*len_x*len_y+j*len_x+i)], &density);
                    fprintf(fp, "%f\n",  density);
                } else {
                    fprintf(fp, "%f\n",  0.0); /* For obstacles */
                }
            }
        }
    }

    if(fclose(fp)){
        char szBuff[80];
        sprintf( szBuff, "Failed to close %s", szFileName );
        ERROR( szBuff );
    }
}

void printField(double *field, int *ncell){
    int x, y, z, i, step_x=ncell[0]+2, step_y=ncell[1]+2, step_z=ncell[2]+2;

    for(x=0;x<step_x;x++){
        for(y=0;y<step_y;y++){
            for(z=0;z<step_z;z++){
                printf("(%d,%d,%d): ",x,y,z);
                for(i=0;i<Q_LBM;i++){
                    printf("%f ",field[Q_LBM*(x+y*step_x+z*step_x*step_y)+i]);
                }
                printf("\n");
            }
        }
    }
}

void printFlagField(int *flagField, int *ncell){
    int x, y, z, step_x=ncell[0]+2, step_y=ncell[1]+2, step_z=ncell[2]+2;

    printf("(y,z)\\x  ");
    for(x=0; x<step_x; x++) {
        printf("%2i ",x);
    }
    printf("\n-------");
    for(x=0; x<step_x; x++) {
        printf("---");
    }
    printf("\n");

    for(z=0;z<step_z;z++){
        for(y=step_y-1;y>=0;y--){
            printf("(%2d,%2d): ",y,z);
            for(x=0;x<step_x;x++){
                printf("%2i ",flagField[x+y*step_x+z*step_x*step_y]);
            }
            printf("\n");
        }
        printf("\n");
    }
}